# Тестовые данные
GET http://localhost:3123/api HTTP/1.1

###

# Офферы
## Получить список предложений

GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###

## Получить список предложений ограниченный по кол-ву

GET http://localhost:4000/offers?count=3 HTTP/1.1
Content-Type: application/json

###

## создать новое предложение


POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json


  {
    "images": [ "img/avatar-angelina.jpg"],
    "title": "Good & house136",
    "description": "Nor again is there anyone who loves or pursues or desires to obtain pa…",
    "type": "house",
    "date": "2022-09-12T18:00:11.162Z",
    "bedrooms": 4,
    "maxAdults": 4,
    "goods": ["Laptop friendly workspace"],
    "host": "6358122e58cb01e36921c84c",
    "rating": 3,
    "isFavorite": false,
    "isPremium": false,
    "price": 30069,
    "latitude": 48.51722, 
    "longitude": 2.81168,
    "city": "Paris",
    "previewImage": "img/apartment-01.jpg"
  }

###

## обновить предложение

PATCH http://localhost:4000/offers/6363bd35f665547b0fb365b1 HTTP/1.1
Content-Type: application/json


  {
    "type": "room",
    "city": "Kondon"
  }

###

## Удалить предложение

DELETE http://localhost:4000/offers/635d49fbdd31693cb2ee11c7 HTTP/1.1
Content-Type: application/json

###

## Получить предложение по id
GET http://localhost:4000/offers/6366828f217d40616770c4a0 HTTP/1.1
Content-Type: application/json

###

## Получить premium предложения по городу
GET http://localhost:4000/offers/premium/Hamburg HTTP/1.1
Content-Type: application/json

###


# Юзеры


## Создать Юзера

POST  http://localhost:4000/users/ HTTP/1.1
Content-Type: application/json

 {
  "email": "romas@mail.ru",
  "name": "EWcdv romas",
  "type": false,
  "password": "12132e"
 }

###

## Авторизация пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "fish@big.local",
  "password": "123456"
}

###

## Отправка аватарки пользователю

POST http://localhost:4000/users/6358122e58cb01e36921c847/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< \Users\Роман\Desktop\testAv.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

# Избранное

## Добавить/удалить в избранное

POST  http://localhost:4000/favorites/6358122f58cb01e36921c859/1 HTTP/1.1
Content-Type: application/json

 {
  "email": "romas@mail.ru"
 }

###

## Получить список избранного

GET  http://localhost:4000/favorites/romas@mail.ru HTTP/1.1
Content-Type: application/json
X-Token: cvw-roma@mail.ru


###

#Comments
## Создать комментарий
POST http://localhost:4000/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Фирменная  сохранена",
  "rating": 2,
  "offerId": "6366828f217d40616770c4a0",
  "userId": "6358122e58cb01e36921c84c"
}

###

## Список комментариев к объявлению
GET http://localhost:4000/offers/6358122f58cb01e36921c859/comments HTTP/1.1

###